#!/usr/bin/env python3
"""Render the public RISC-V frontier README from frontier-status.json.

The README is customer-facing, so it should not be hand-edited into drift. This
script keeps the prose and tables tied to the machine-readable status file and
also verifies that every local receipt JSON under receipts/ is referenced.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
STATUS_PATH = ROOT / "frontier-status.json"
README_PATH = ROOT / "README.md"


def _load_status() -> dict[str, Any]:
    with STATUS_PATH.open() as f:
        data = json.load(f)
    if data.get("schema") != "athanor_riscv_frontier_status_v1":
        raise SystemExit(f"unexpected status schema in {STATUS_PATH}")
    for key in ("claim_policy", "accepted_artifacts", "rejected_tradeoffs", "scouted_cores"):
        if key not in data:
            raise SystemExit(f"{STATUS_PATH} missing required key: {key}")
    return data


def _link(label: str, target: str) -> str:
    return f"[{label}]({target})"


def _evidence_link(target: str) -> str:
    label = Path(target).name if target.startswith("receipts/") else "artifact package"
    return _link(label, target)


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    out.extend("| " + " | ".join(row) + " |" for row in rows)
    return out


def _count_by(rows: list[dict[str, Any]], key: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        value = str(row[key])
        counts[value] = counts.get(value, 0) + 1
    return dict(sorted(counts.items()))


def _receipt_refs(data: dict[str, Any]) -> set[str]:
    refs: set[str] = set()
    for section in ("accepted_artifacts", "rejected_tradeoffs"):
        for row in data[section]:
            evidence = str(row.get("evidence", ""))
            if evidence.startswith("receipts/"):
                refs.add(evidence)
    return refs


def _validate_receipt_coverage(data: dict[str, Any]) -> None:
    receipt_files = {
        str(path.relative_to(ROOT))
        for path in (ROOT / "receipts").rglob("*.json")
    }
    refs = _receipt_refs(data)
    missing = sorted(refs - receipt_files)
    unreferenced = sorted(receipt_files - refs)
    problems = []
    if missing:
        problems.append("referenced receipt files are missing:\n  " + "\n  ".join(missing))
    if unreferenced:
        problems.append("receipt files are not indexed in frontier-status.json:\n  " + "\n  ".join(unreferenced))
    if problems:
        raise SystemExit("\n\n".join(problems))


def render(data: dict[str, Any]) -> str:
    _validate_receipt_coverage(data)
    policy = data["claim_policy"]
    accepted = data["accepted_artifacts"]
    rejected = data["rejected_tradeoffs"]
    scouted = data["scouted_cores"]
    accepted_counts = _count_by(accepted, "core")
    rejected_counts = _count_by(rejected, "core")
    not_claimed = policy.get("not_claimed", [])
    status_defs = policy.get("status_definitions", {})
    metric_defs = policy.get("metric_definitions", {})

    lines: list[str] = [
        "# Athanor RISC-V Frontier",
        "",
        "<!-- AUTO-GENERATED by scripts/render_frontier_readme.py; edit frontier-status.json instead. -->",
        "",
        "This repository is the public umbrella index for Athanor's open RISC-V optimization work. "
        "It tracks accepted evidence, rejected tradeoffs, and active exploration across open cores. "
        "Every row below is generated from [`frontier-status.json`](frontier-status.json), so the "
        "customer-facing README changes only when the machine-readable status changes.",
        "",
        f"Last status update: `{data['updated_utc']}`.",
        "",
        "## Current Public Status",
        "",
        str(policy["public_summary"]),
        "",
        "Accepted artifacts by core:",
        "",
    ]
    lines.extend(f"- `{core}`: {count}" for core, count in accepted_counts.items())
    lines.extend([
        "",
        "Rejected tradeoffs by core:",
        "",
    ])
    lines.extend(f"- `{core}`: {count}" for core, count in rejected_counts.items())
    lines.extend([
        "",
        "Do not over-read the table:",
        "",
    ])
    lines.extend(f"- No {claim}." for claim in not_claimed)
    lines.extend([
        "",
        "## How This Stays Current",
        "",
        "- Add or update receipt JSON under `receipts/<core>/{accepted,rejections}/`, or link to a public artifact package in the owning core repo.",
        "- Update `frontier-status.json` with the row, core, scope, evidence link, and boundary wording.",
        "- Run `python3 scripts/render_frontier_readme.py --check` before merging.",
        "- CI runs the same check and fails if the README is stale, a linked receipt is missing, or a receipt JSON is not indexed.",
        "",
        "This keeps wins for existing cores such as Ibex, CV32E40P, and OpenC910 visible without hand-editing "
        "the README. The next automation step is for each owning core repo to publish the same status JSON shape "
        "so this umbrella can ingest it instead of copying summaries by hand.",
        "",
        "## How To Read This Page",
        "",
    ])
    for key in (
        "accepted_whole_core_result",
        "accepted_module_artifact",
        "accepted_module_local_artifact",
        "accepted_scope_typed_optimization",
        "rejected_tradeoff",
        "exploratory_lead",
        "receipt",
    ):
        if key in status_defs:
            lines.append(f"- {status_defs[key]}")
    lines.extend([
        "",
        "Metric vocabulary:",
        "",
    ])
    for key in (
        "rtl",
        "area",
        "wns",
        "data_arrival_max_delay",
        "toggle",
        "saif",
        "yosys_equivalence",
        "miter",
        "bad_mutant",
        "oss_fv",
        "cold_replay",
        "selected_flow",
        "generic_yosys_no_abc",
        "timing_groups",
        "ppa",
        "activity",
        "detector",
        "preflight",
    ):
        if key in metric_defs:
            label = key.replace("_", " ")
            lines.append(f"- **{label}**: {metric_defs[key]}")
    lines.extend([
        "",
        "## Accepted Evidence",
        "",
    ])
    lines.extend(_table(
        ["Core", "Artifact", "Status", "Scope / Result", "Evidence"],
        [
            [
                str(row["core"]),
                f"`{row['artifact']}`",
                str(row["display_status"]),
                str(row["summary"]),
                _evidence_link(str(row["evidence"])),
            ]
            for row in accepted
        ],
    ))
    lines.extend([
        "",
        "## Rejected Tradeoffs",
        "",
        "These are public because they are useful engineering evidence, not because they are optimization claims. "
        "Each row improved at least one checked axis and failed another required axis.",
        "",
    ])
    lines.extend(_table(
        ["Core", "Candidate", "Why It Was Rejected", "Evidence"],
        [
            [
                str(row["core"]),
                f"`{row['candidate']}`",
                str(row["summary"]),
                _evidence_link(str(row["evidence"])),
            ]
            for row in rejected
        ],
    ))
    lines.extend([
        "",
        "## Exploratory Work",
        "",
        "These rows are reconnaissance, baselines, or candidates that still need more evidence. "
        "They are not optimization claims.",
        "",
    ])
    lines.extend(_table(
        ["Core", "Current state", "Best current lead", "Next evidence gate"],
        [
            [
                str(row["core"]),
                str(row.get("display_status", row.get("status", ""))),
                str(row.get("current_lead", row.get("repo", ""))),
                str(row.get("next_gate", row.get("current_gate", ""))),
            ]
            for row in scouted
        ],
    ))
    lines.extend([
        "",
        "Machine-readable status lives in [`frontier-status.json`](frontier-status.json).",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if README.md is not the rendered output")
    args = parser.parse_args()
    data = _load_status()
    rendered = render(data)
    if args.check:
        current = README_PATH.read_text()
        if current != rendered:
            print("README.md is stale; run scripts/render_frontier_readme.py", file=sys.stderr)
            return 1
        return 0
    README_PATH.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
